repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
        files: '.*\.pyi?$'
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: ['flake8-bugbear==23.1.20']
  #       files: '.*\.pyi?$'
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: '.*\.pyi?$'
  - repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
        files: '.*\.pyi?$'
