name: TestSuite

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        python-version: ["3.10", "3.11"]
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: pip3 install --user -e '.[dev]'
      - name: Setup default linchemin configuration
        run: linchemin_configure
      - name: Run Tests
        run: python -m pytest -v
